name: Basic pull request
description: A basic pull request
title: "Please fill out this field"
labels: [needs_labelling]
assignees:
  - electron271
  - SoupDevHub
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this PR!
    validations:
      required: false
  - type: textarea
    id: Information
    attributes:
      label: General information
      description: Please put some basic onformation
      placeholder: Tell us what you put!
      value: "This PR.."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: OS
      description: What OS are you running?
      options:
        - Windows (Tested)
        - MacOS (Needs to be tested)
        - Linux (Tested)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
